### ISSUE TITLE
markdown文件的链接如果带了注释总是迁移失败

### ISSUE THREAD

**Issue by iplaypi** [PicGo/picgo-plugin-pic-migrater#1]
1、如果链接是这样的：!\[在浏览器中打开图片可以正常显示](https://ws1.sinaimg.cn/large/b7f2e3a3gy1g2hfpvew8yj212p0k2q3i.jpg "在浏览器中打开图片可以正常显示") ，迁移失败。
2、如果链接是这样的，迁移成功：!\[在浏览器中打开图片可以正常显示](https://ws1.sinaimg.cn/large/b7f2e3a3gy1g2hfpvew8yj212p0k2q3i.jpg) 。

这个要怎么解？

**Comment by Molunerfinn** [comment]
这个应该是正则匹配提取URL的问题。
https://github.com/PicGo/picgo-plugin-pic-migrater/blob/master/src/lib/FileHandler.ts#L26
之后会修复
