### ISSUE TITLE
md无法正常迁移

### ISSUE THREAD

**Issue by wky809982944** [PicGo/picgo-plugin-pic-migrater#12]
我觉你肯定是在mac下编辑的
我的windows能迁移图片但是无法生产新的md
linux下能迁移图片和但是不会生成新的md，是直接把原来的md图片路径覆盖掉了

**Comment by Molunerfinn** [comment]
我用的Windows

**Comment by nowyouseeit** [comment]
设置 newFileSuffix 没有产生新的 md，系统 windows

**Comment by Molunerfinn** [comment]
查看PicGo的日志，看看报了什么错？

**Comment by nowyouseeit** [comment]
> 查看PicGo的日志，看看报了什么错？
![image](https://user-images.githubusercontent.com/31727621/68099310-c4e3fc00-fefc-11e9-976a-a1eb15e13231.png)
![image](https://user-images.githubusercontent.com/31727621/68099320-d62d0880-fefc-11e9-965d-aac3adecffe3.png)
好像没有报错。

**Comment by nowyouseeit** [comment]
公司电脑直接覆盖路径，也不会产生新md,系统 windows
![image](https://user-images.githubusercontent.com/31727621/68116265-58d1ba00-ff35-11e9-9be8-a6c84cfc2020.png)

**Comment by Molunerfinn** [comment]
回头我会找个时间看看原因，最近这段时间比较忙，抱歉哈

**Comment by nowyouseeit** [comment]
嗯嗯，辛苦！

**Comment by cooper1x** [comment]
我也是遇到了这个问题。

**Comment by doupip** [comment]
picgo2.2.0 基本不能用了. windows. 2020-01-02 15:27:59 [PicGo WARN] failed

**Comment by Molunerfinn** [comment]
> picgo2.2.0 基本不能用了. windows. 2020-01-02 15:27:59 [PicGo WARN] failed

贴个完整的日志才能看出问题...不迁移的情况下你直接上传图片可以么

**Comment by doupip** [comment]
> > picgo2.2.0 基本不能用了. windows. 2020-01-02 15:27:59 [PicGo WARN] failed
> 
> 贴个完整的日志才能看出问题...不迁移的情况下你直接上传图片可以么

日志全开的,里面就只有这一行, 默认选的SM.MS图床,是可以正常上传的.
其他插件如picgo-plugin-gitee-uploader 貌似也有问题,同步和拉取都OK但用起来就总报错.

**Comment by Molunerfinn** [comment]
> > > picgo2.2.0 基本不能用了. windows. 2020-01-02 15:27:59 [PicGo WARN] failed
> > 
> > 
> > 贴个完整的日志才能看出问题...不迁移的情况下你直接上传图片可以么
> 
> 日志全开的,里面就只有这一行, 默认选的SM.MS图床,是可以正常上传的.
> 其他插件如picgo-plugin-gitee-uploader 貌似也有问题,同步和拉取都OK但用起来就总报错.

其他插件的问题要让对应的开发者去看一下是什么问题。

你这个只有 `failed` 不合理啊， `migrating` 这些都没有么
![image](https://user-images.githubusercontent.com/12621342/71658178-ef77f700-2d7d-11ea-970d-28119253c122.png)

**Comment by Molunerfinn** [comment]
另外 `failed` 是在上传过程中出错了才会这样。可以贴一下配置文件么，看看配置文件有没有什么问题

**Comment by doupip** [comment]
> 另外 `failed` 是在上传过程中出错了才会这样。可以贴一下配置文件么，看看配置文件有没有什么问题

我重装了picgo(包含删除了配置), 仔细看了下会间歇性的上传失败, 重启下应用就又可以上传.
用插件迁移显示成功,但没有新命名的文件(设置的_new),旧文件中链接实际也无变化. 日志中有新迁移的链接,相册中没有.先不纠结这个问题了,感谢!

**Comment by Molunerfinn** [comment]
> > 另外 `failed` 是在上传过程中出错了才会这样。可以贴一下配置文件么，看看配置文件有没有什么问题
> 
> 我重装了picgo(包含删除了配置), 仔细看了下会间歇性的上传失败, 重启下应用就又可以上传.
> 用插件迁移显示成功,但没有新命名的文件(设置的_new),旧文件中链接实际也无变化. 日志中有新迁移的链接,相册中没有.先不纠结这个问题了,感谢!

SMMS现在对免费的用户上传图片有频率限制了，所以报错可能是那边给的错误信息。

至于没有生成新命名的文件，这个我需要看看是为什么。想问一下你是使用了文件夹迁移还是文件迁移？

**Comment by doupip** [comment]
用的是文件

**Comment by Molunerfinn** [comment]
> 用的是文件

没有生成新文件的问题已经定位，下个版本会修复

**Comment by Molunerfinn** [comment]
更新至1.2.0版本即可
