### ISSUE TITLE
图片URL转义问题

### ISSUE THREAD

**Issue by wky809982944** [PicGo/picgo-plugin-pic-migrater#20]
![image](https://user-images.githubusercontent.com/44250397/72239406-ef001b80-361b-11ea-945b-556510c7eee8.png)
今天才发现勾选插入时自动转义图片URL会导致图片找不到所以无法转换

**Comment by Molunerfinn** [comment]
这个是typora的问题。

**Comment by Molunerfinn** [comment]
另外Windows的文件路径分隔符问题会在下个版本修复
