### ISSUE TITLE
win10 picgo 2.2.2 migrater 插件选择文件后，如果不选择，则也会触发一次上传

### ISSUE THREAD

**Issue by l-souljourney** [PicGo/picgo-plugin-pic-migrater#21]
![image](https://user-images.githubusercontent.com/13096524/74589153-ba79e800-503d-11ea-851e-20c5c1aabc27.png)

如图所示，我没截图出来右键的那个菜单，就是如果我右键打开一个资源管理器，我没选择文件，点击了取消，然后也会自动触发一次上传接口。

看看是优化问题还是。

PS: 这个功能真是神器，期待更多好的优化出现。

**Comment by Molunerfinn** [comment]
这个应该是个bug，后续版本会修复。

**Comment by Molunerfinn** [comment]
目前对太多图片同时上传的支持程度还不够。未来会优化。目前建议一次性迁移5张图片为佳。

**Comment by Molunerfinn** [comment]
更新v1.2.2版本插件，已经修复
