### ISSUE TITLE
【功能需求】希望可以增加转换地址添加后缀比如oss的 !sytle01这类

### ISSUE THREAD

**Issue by l-souljourney** [PicGo/picgo-plugin-pic-migrater#23]
首先感谢作者，使用良好。

希望可以增加自定义链接功能，比如一个地址是 https://www.a.com/111.jpg 的md地址。修改之后是https://www.b.com/111.jpg 这个没问题。主要是改变之后是上传到了oss的图床上。然后因为oss或者cos上需要加上自定义样式用于压缩和裁剪，也就是!style01 或者其他方式的后缀。那么希望自动转换之后可以变成

https://www.b.com/111!style01 这样的方式，也就是可以自定义处理一下域名转换之后的后缀。

感谢感谢。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/80699258-40221580-8b0e-11ea-9689-82d694e2cff3.png)
COS的后续版本会加上。
