### ISSUE TITLE
迁移Onedrive图片后，无法更新md文件

### ISSUE THREAD

**Issue by kanshurichard** [PicGo/picgo-plugin-pic-migrater#25]
测试代码：

`
Test Test Test
21211111
![](https://storage.live.com/items/30D9F9A348AC208B!20467:/01.png?authkey=AMWPepY4tg0HgcY)
AAAAAA
121333
`

图片可以顺利上传到Github或sm.ms，但生成的_new文件里面还是原来的图片URL。

使用APP内下载的GUI版本

**Comment by Molunerfinn** [comment]
可能是正则匹配的问题，之后有时间看看啥问题
