### ISSUE TITLE
插件只是上传至新图床并没有替换文件

### ISSUE THREAD

**Issue by zhangferry** [PicGo/picgo-plugin-pic-migrater#28]
我用的mac pic-migrater1.2.0版本，我单选文件，可以上传md中的图片至图床指定目录，也生成了带_new的新md，但新md并没有替换图片，还是旧图片，这是为什么呢？

**Comment by Molunerfinn** [comment]
原始md文件贴出来看看？

**Comment by zhangferry** [comment]
@Molunerfinn https://github.com/zhangferry/NoteBook/blob/master/hackintosh_os_update.md 这个是原md。
今天又试了下这个md，迁移全部失败了，图片都是在github上的。昨天试的那篇有问题的md被我手动替换了

**Comment by Molunerfinn** [comment]
这个迁移失败可能是网络问题，github原始链接没有cdn，所以可能存在网络超时导致迁移失败。昨天那个迁移成功没有替换文本的md才是关键

**Comment by zhangferry** [comment]
https://github.com/zhangferry/NoteBook/blob/master/nRF-DFU-upgrade.md 这篇md你试下，也遇到了迁移成功却没有替换的问题，这里的图片用的掘金的图床。我发现掘金图片后缀都不带图片格式的后缀，不清楚是不是判断条件跟这个有关。

**Comment by Molunerfinn** [comment]
OK，最近有空的时候看一下

**Comment by declan-haojin** [comment]
同样的问题+1，求解决，谢谢！

**Comment by Molunerfinn** [comment]
更新v1.2.2版本插件，已经修复
