### ISSUE TITLE
为什么会出错？

### ISSUE THREAD

**Issue by HypatiaT** [PicGo/picgo-plugin-pic-migrater#29]
<img width="1024" alt="picgo2" src="https://user-images.githubusercontent.com/23455534/84599300-928f7980-aea3-11ea-8959-c7d4cdd185b7.png">
<img width="618" alt="picgo" src="https://user-images.githubusercontent.com/23455534/84599302-94593d00-aea3-11ea-9d4b-f5ced42e42db.png">

为什么会出错？设置成功之后，和出现“404 branch not found”。为什么？

**Comment by Molunerfinn** [comment]
因为你的分支是main
