### ISSUE TITLE
可否支持转载文章中微信公众号图片，上传其他图床

### ISSUE THREAD

**Issue by yuhw2001** [PicGo/picgo-plugin-pic-migrater#30]
譬如：
https://mmbiz.qpic.cn/mmbiz_jpg/KdAStmiazbn8Y5PTUUibFibpCicwYfvbic7olzicTsXCvhcjRR3OegCPEcMyS08ZVta67TRuKItkOicPCl3JZ0aKHIdZA/640
图片网址格式一般都是一致的。
粘贴到typora中
自动上传自有图床

谢谢！

**Comment by Molunerfinn** [comment]
微信公众平台的图片有防盗链。PicGo无法处理防盗链的图片
