### ISSUE TITLE
显示已安装，但却没有右击菜单，重新切换到插件列表显示无插件

### ISSUE THREAD

**Issue by rendacode** [PicGo/picgo-plugin-pic-migrater#35]
![image](https://user-images.githubusercontent.com/15043653/101109578-2b60af80-3612-11eb-9bad-f05892bfbd33.png)

重新切换到插件列表显示无插件，或者重启软件之后还是显示未安装，多次尝试都是如此，请问这个是什么原因呢？

![image](https://user-images.githubusercontent.com/15043653/101109669-6531b600-3612-11eb-9017-7d28fb66ecc5.png)

Mac版本：
![image](https://user-images.githubusercontent.com/15043653/101109842-b9d53100-3612-11eb-88e1-ec6eb57cee08.png)

picgo版本：2.2.2和最新的测试版都测试过，安装migrater不成功

试着安装其他插件，可以成功
![image](https://user-images.githubusercontent.com/15043653/101112759-002d8e80-3619-11eb-9c7e-cca71051b97e.png)

**Comment by Molunerfinn** [comment]
可以试试打开picgo配置文件所在目录（可以在PicGo设置->打开配置文件 找到配置文件所在的目录），在这个目录下手动通过命令行安装

`npm install picgo-plugin-pic-migrater --save`。安装结束后，重启picgo，应该就能看到插件了。

**Comment by rendacode** [comment]
安装成功了，谢谢。
在mac ~/Library/ApplicationSupport/picgo  下执行安装命令：
`npm install picgo-plugin-pic-migrater --save`
安装之后重启pidgo依旧没看到插件，重启电脑之后也没有看到这个插件，
然后在mac ~/Library/ApplicationSupport/picgo  下执行卸载命令：
`npm uninstall  picgo-plugin-pic-migrater`
在执行安装命令，重启picgo就看到这个插件了。
