### ISSUE TITLE
请问通过npm包直接引入picgo怎么用这个插件呢？

### ISSUE THREAD

**Issue by flytam** [PicGo/picgo-plugin-pic-migrater#37]
好像没找到相关文档

**Comment by Molunerfinn** [comment]
暂未开放 PluginLoader。 有开放PluginHandler，可以通过PluginHandler来安装、卸载插件。
https://picgo.github.io/PicGo-Core-Doc/zh/api/#pluginhandler

**Comment by Molunerfinn** [comment]
新版本已经可以使用PluginLoader加载插件了。

https://picgo.github.io/PicGo-Core-Doc/zh/api/#pluginloader-registerplugin-pluginname-plugin

**Comment by Molunerfinn** [comment]
Nodejs项目的使用可以参考readme：
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/12621342/186564175-f7823205-d9b9-4f7c-a357-ab66d290ded7.png">
