### ISSUE TITLE
最新1.2.1版本，能够成功上传文件，但是无法生成新md文件

### ISSUE THREAD

**Issue by purequant** [PicGo/picgo-plugin-pic-migrater#38]
我用的是腾讯云存储，之前1.2.0版本正常，一段时间没有该插件，现在更新后发现出问题了。选择想要迁移的md文件上传图片后，一直卡住：

![image](https://user-images.githubusercontent.com/26440503/103796231-e9e47980-5081-11eb-92b6-f57a6b9f1a4a.png)

![image](https://user-images.githubusercontent.com/26440503/103796209-e51fc580-5081-11eb-92dd-999b29cbded4.png)

检查腾讯云发现文件已经成功上传，但是无法生成新的md文件。重启软件后，相册中也记录上传的图片。
---
命令行版我也尝试过，情况一样，卡住无法自动生成新的md文件：
![image](https://user-images.githubusercontent.com/26440503/103801516-cd980b00-5088-11eb-90a1-27bd3ed380b4.png)

**Comment by Molunerfinn** [comment]
有空的时候会排查一下问题

**Comment by Molunerfinn** [comment]
可以给个出问题的markdown文件么（可以写一个能复现的demo）？有可能跟具体的写法有关，有个demo好排查点

**Comment by purequant** [comment]
感谢您热情的回复！那我就以命令行版为例，说一下经过：
1. 我在 vscode 中打开包含需要迁移的md文件的名为 **测试picgo上传** 的文件夹（应该也叫在当前工作空间中打开文件夹）。
2. 然后，打开 **测试picgo上传.md** 文档，并用快捷键启动**PowerShell** 终端。
3. 然后在终端中运行上传命令，并得到如下结果（部分个人信息，我以省略号代替）：
   
   ```PowerShell
   # 14747 at SUPER-ALPHA in G:\OneDrive\……\测试picgo上传 inside env:base [18:23:35]
   ➜ picgo migrate ./测试picgo上传.md
   [PicGo INFO]: Migrating...
   [PicGo INFO]: Before transform
   [PicGo INFO]: Transforming...
   [PicGo INFO]: Before upload
   [PicGo INFO]: Uploading...
   [PicGo SUCCESS]:
   https://upload-images-…….cos.ap-shanghai.myqcloud.com/test/%E6%B5%8B%E8%AF%95%E5%9B%BE%E7%89%87_2021-01-07-00-36-53.png
   ```
1. 最终PowerShell如之前描述卡住，但是经检查发现图片已经成功上传，只是无法成功生成个迁移后的md文件。

相关测试文件夹在此：[测试picgo上传.zip](https://github.com/PicGo/picgo-plugin-pic-migrater/files/5795207/picgo.zip)

**Comment by Yhooooo** [comment]
我也出现了和楼主一样的问题，我用的插件的方式。用的gitee图床，图片都上传上去了，但是最终的md文件没有生成。

**Comment by Yhooooo** [comment]
上传图片完毕后PicGo卡死，只能强行结束

**Comment by Molunerfinn** [comment]
很抱歉，最近没时间看这块的问题。等PicGo2.3.0的正式版发出之后，会逐步解决官方插件的一些适配问题

**Comment by bsszds** [comment]
我用GitHub图床，发现图片已经上传到GitHub图床，但是到了修改md文件图片链接时，修改了第一个，接着插件的程序就卡住了，没有生产_new的文件

**Comment by Molunerfinn** [comment]
卡死的地方已经找到，近期会发个新版本解决
