### ISSUE TITLE
图片没有迁移成功

### ISSUE THREAD

**Issue by Lupeipei** [PicGo/picgo-plugin-pic-migrater#4]
环境：
Mac 10.14.5， PicGo 2.1.2 pic-migrater 1.0.2
问题描述：
我的markdown文件里面的图片全是新浪图床上的，格式都类似这样
`![](https://ws1.sinaimg.cn/large/xxxx.png)`

配置里面，include写的是sinaimg.cn,选择文件夹后, 新生成的markdown文件，全部是那些本来就没有图片链接的文件，而带图片链接的文件则一个都没有生成新的文件，是我哪里配置错了吗还是版本问题？

**Comment by Molunerfinn** [comment]
选择文件夹可能还有点问题。你先试试选择单个文件的。批量迁移可能会因为中间一些错误导致整体失效。你可以先用用选择文件迁移的功能。之后我会找时间修复一下

**Comment by Lupeipei** [comment]
刚试了，选择文件去迁移，结果仍然不行，弹出信息：迁移完成，图片迁移成功0张，迁移失败1张。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/59140274-0ca63c00-89ce-11e9-9a63-b67ba0a853ee.png)
我这边测试文件迁移是没问题的：
这是我的源文件：

```md
![](https://ws1.sinaimg.cn/large/8700af19ly1fk1eksl51kj21z20ogjyo.jpg)
![](https://i.loli.net/2019/02/09/5c5e1556af49b.png)
```

**Comment by Molunerfinn** [comment]
检查一下你使用的默认上传的图床配置是否正确，是否可以正常上传图片。以及你可以打开日志文件查看日志看看迁移错误的报错日志：

![image](https://user-images.githubusercontent.com/12621342/59140324-8dfdce80-89ce-11e9-93f6-a05f69f168b5.png)

以下是我的日志：

![image](https://user-images.githubusercontent.com/12621342/59140332-abcb3380-89ce-11e9-8eab-99e8c7bfe369.png)

**Comment by Lupeipei** [comment]
非常感谢耐性答复，我看了日志，找到为什么无法迁移了，怪自己手贱设置了代理，现在已经可以顺利迁移啦，谢谢！
