### ISSUE TITLE
迁移图片到GitHub图床的时候会出现Picgo未响应卡死的情况

### ISSUE THREAD

**Issue by LvShuaiChao** [PicGo/picgo-plugin-pic-migrater#43]
![image](https://user-images.githubusercontent.com/35528109/127993157-8a54b144-3522-4a50-9518-7c29e5e02cd8.png)
我试了过几次，一直是这种问题，我的系统的是Win10 64位，我的picgo是2.21版本的
![image](https://user-images.githubusercontent.com/35528109/127993306-684ab541-073b-41ca-b8cc-fe89d732bb07.png)
插件也进行了设置
![image](https://user-images.githubusercontent.com/35528109/127993364-11afe866-52da-45d3-9b5d-7c4dd2f775d9.png)

但是不明白为什么会出现这种问题？

**Comment by bsszds** [comment]
我也是

**Comment by ConanSteve** [comment]
我也一直卡死，本以为是图形界面卡死，然后换成命令行迁移，还是照样卡死
<img width="777" alt="image" src="https://user-images.githubusercontent.com/28643122/161214743-c23a6ddc-07f8-40cc-a8c8-76b16b48360e.png">

**Comment by Ruth-Seven** [comment]
我发现把当我本地图片的链接从“xx.jpg”改成“./xx.jpg”就成功上传，成功复制新文件了

**Comment by opersdev** [comment]
我也会卡死 
![image](https://user-images.githubusercontent.com/38125526/173268875-8f9eb244-5895-4d4d-b7c1-dd71c0d4cdfb.png)

**Comment by Molunerfinn** [comment]
更新v1.2.2版本插件，已经修复
