### ISSUE TITLE
图片如果是html标签插入的无法迁移

### ISSUE THREAD

**Issue by singledoggy** [PicGo/picgo-plugin-pic-migrater#45]
因为用html标签插入图片可以比较方便的配置大小，e.g.:
```
<img src="./xxx.png" width = "300" height = "200" alt="图片名称" align=center />
```
能否考虑添加对标签的支持

**Comment by Molunerfinn** [comment]
可以，后续会考虑支持

**Comment by singledoggy** [comment]
针对我自己的标签目前我是用简单的正则替换成markdown格式再进行后处理的，这是一个最小化的例子，可能不能覆盖所有的标签情况
```
import re
a='<img src="./xxx.png" width = "300" height = "200" alt="图片名称" align=center />'
pic_url = re.compile('(<img src=")(.*?)(".*)(>)')
a=re.sub(pic_url,r"![](\2)",a)
```

**Comment by Molunerfinn** [comment]
单纯的正则匹配会遇到很多边界case。这边打算引入markdown的parser来处理，比如 [marked](https://github.com/markedjs/marked)，通过AST的方式来实现

**Comment by Molunerfinn** [comment]
这个预计会在1.3.0版本里做支持，因为对底层实现是个非常大的改动

**Comment by Molunerfinn** [comment]
看了一下markdown的AST实现，对于img标签的处理也都是处理成 `html` 节点。- -所以还是要用正则匹配。我处理一下

**Comment by singledoggy** [comment]
感谢开发和维护！

**Comment by Molunerfinn** [comment]
v1.3.0已经支持，请配合最新的PicGo或者PicGo-Core版本使用
