### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xqa** [PicGo/picgo-plugin-pic-migrater#49]
https://github.com/PicGo/picgo-plugin-pic-migrater/blob/532ccbcf6629a0ed8fde0ad90353123c635d489e/src/lib/Migrater.ts#L44

这一行有问题，`&&`的优先级高于`||` ,这里好像是之前的一个[合并请求](https://github.com/PicGo/picgo-plugin-pic-migrater/issues/43#issue-958923591)写错了，我发现好像那个[卡死的问题](https://github.com/PicGo/picgo-plugin-pic-migrater/issues/43#issue-958923591)就是这个引起的。

**Comment by Molunerfinn** [comment]
感谢 回头会看看

**Comment by Molunerfinn** [comment]
更新v1.2.2版本插件，已经修复
