### ISSUE TITLE
转义的图片路径无法上传

### ISSUE THREAD

**Issue by kaTelance** [PicGo/picgo-plugin-pic-migrater#54]
在使用Obsidian插入图片后，Markdown图片路径为转义后的路径，如 ![](assets/Pasted%20image%2020220716034308.png)，实际资源为 assets 文件夹下的 `Pasted image 20220716034308.png` ,这种情况会报路径错误

**Comment by Molunerfinn** [comment]
请给一个可以复现的markdown文件方便复现问题。

**Comment by kaTelance** [comment]
https://wwk.lanzouv.com/ieRMj0ezfqab
使用Typora或者Obsidian都能够正常展示，其中第一张图片路径存在空格转义，无法上传成功

**Comment by Molunerfinn** [comment]
收到，应该有办法处理

**Comment by kaTelance** [comment]
ok，不知有无将图床图片批量下载到本地，并将文档中的链接全部替换成本地路径的插件，这样markdown图片迁移的问题就解决了

**Comment by Molunerfinn** [comment]
暂时没有，不过后续有时间了也可以考虑实现一下。

**Comment by Molunerfinn** [comment]
> ok，不知有无将图床图片批量下载到本地，并将文档中的链接全部替换成本地路径的插件，这样markdown图片迁移的问题就解决了

有个开发者开发了个能本地备份的插件，不知道是否可以使用。https://github.com/Redns/picgo-plugin-autobackup

**Comment by kaTelance** [comment]
> > ok，不知有无将图床图片批量下载到本地，并将文档中的链接全部替换成本地路径的插件，这样markdown图片迁移的问题就解决了
> 
> 有个开发者开发了个能本地备份的插件，不知道是否可以使用。https://github.com/Redns/picgo-plugin-autobackup
感谢 这个好像主要是自动备份的作用，没办法转文档中图床图片并替换链接

**Comment by Molunerfinn** [comment]
更新1.3.2版本即可
