### ISSUE TITLE
m1芯片mac点击选择文件没有反应

### ISSUE THREAD

**Issue by cooper1x** [PicGo/picgo-plugin-pic-migrater#56]
无法出现选择文件和选择文件夹弹框，目前picgo是2.3.1，插件是1.3.2

**Comment by Molunerfinn** [comment]
手头没有M1的机器没法复现。有啥错误日志么？如果日志文件里没有相关日志，可以退出picgo，用命令行启动picgo，然后查看点击「选择文件」的时候，命令行中有没有什么日志

**Comment by cooper1x** [comment]
用命令行怎么启动picgo呢？我看了这个文档，没有找到启动相关的参数，只看到了debug。
[CLI命令 | PicGo-Core](https://picgo.github.io/PicGo-Core-Doc/zh/guide/commands.html#config-set)

**Comment by Molunerfinn** [comment]
你看的文档是 PicGo-Core的，应该看 PicGo 客户端的：https://picgo.github.io/PicGo-Doc/zh/guide/advance.html#%E5%91%BD%E4%BB%A4%E8%A1%8C%E4%B8%8A%E4%BC%A0

把 `upload` 去掉，就能单独启动 PicGo。前提是先退出当前在运行的 PicGo

**Comment by Molunerfinn** [comment]
有一个点是，你是否已经配置了插件？如果没配置插件，理论上是会有个通知告诉你先配置才能使用功能。
<img width="560" alt="image" src="https://user-images.githubusercontent.com/12621342/210726878-a31787d8-5902-4f9c-a731-a9ae84453a2d.png">

**Comment by cooper1x** [comment]
@Molunerfinn 我在intel芯片的mac试过，picgo命令无法启动picgo，只能手动打开启动。插件的提醒通知也没有。m1的我待会儿再试试。

**Comment by Molunerfinn** [comment]
> @Molunerfinn 我在intel芯片的mac试过，picgo命令无法启动picgo，只能手动打开启动。插件的提醒通知也没有。m1的我待会儿再试试。

无法启动？命令行有啥报错

**Comment by Molunerfinn** [comment]
> 你看的文档是 PicGo-Core的，应该看 PicGo 客户端的：https://picgo.github.io/PicGo-Doc/zh/guide/advance.html#%E5%91%BD%E4%BB%A4%E8%A1%8C%E4%B8%8A%E4%BC%A0
> 
> 
> 
> 把 `upload` 去掉，就能单独启动 PicGo。前提是先退出当前在运行的 PicGo

你看了我这条回复里的文档了吗？能手动启动的话，命令行是肯定能启动的，前提是

1. 要退出当前的PicGo
2. 命令要输入正确

<img width="768" alt="image" src="https://user-images.githubusercontent.com/12621342/210735279-b1b58e7f-d4e5-4e83-a913-5361f5bb5861.png">

**Comment by cooper1x** [comment]
抱歉，我没有带上路径，错误的直接使picgo命令，跟core弄混了。m1那台电脑是朋友的，他现在在忙，我晚点远程他电脑看下日志信息。

**Comment by cooper1x** [comment]
解决了，的确是先前没有配置插件。通知默认是关闭的，M1的安装包下载后会提示损坏，就会有这个问题。目前他的电脑系统是MacOS 13.1
<img width="280" alt="image" src="https://user-images.githubusercontent.com/9080789/210760719-c1cbb785-bfe9-4e52-b6a7-8ba8c191a489.png">

**Comment by Molunerfinn** [comment]
> 解决了，的确是先前没有配置插件。通知默认是关闭的，M1的安装包下载后会提示损坏，就会有这个问题。目前他的电脑系统是MacOS 13.1 <img alt="image" width="280" src="https://user-images.githubusercontent.com/9080789/210760719-c1cbb785-bfe9-4e52-b6a7-8ba8c191a489.png">

提示损坏，请查看 PicGo 的 FAQ最后一条谢谢。

**Comment by cooper1x** [comment]
嗯嗯，损坏是解决了，用命令修复了，只是似乎默认的通知是关闭的，也可能是设置问题。

**Comment by Molunerfinn** [comment]
> 嗯嗯，损坏是解决了，用命令修复了，只是似乎默认的通知是关闭的，也可能是设置问题。

通知需要给权限，如果一开始没给权限，后续到macOS系统的权限中心自行给通知权限即可。
