### ISSUE TITLE
关于newFilePrefix

### ISSUE THREAD

**Issue by luoxiao** [PicGo/picgo-plugin-pic-migrater#6]
嗨，
很感谢你的插件。
能否不设置 newFilePrefix呢，
我的问题，因为MD文件太多了，如果每个都生成一个新MD文件，还得手动替换。这又是一个不小的工程量。
我的期望：自动替换图片路径就行了，不需要生成新的MD文件。
这样就完美了吧。
真诚的感谢 作者 ~

**Comment by Molunerfinn** [comment]
你设置成空字符串就行。在PicGo的UI界面无法设置，你可以打开配置文件手动设置即可。

**Comment by luoxiao** [comment]
感谢这么快回复，
我按的建议，data.json设置了空串，
还是会生成“README_new.md” 这样的MD。

**Comment by Molunerfinn** [comment]
哦不好意思，我在某次提交的时候加了个默认值，下个版本我会将它去掉

**Comment by luoxiao** [comment]
希望能早日使用到。
这个插件帮了大忙，
真诚感谢，
