### ISSUE TITLE
Windows, 图片上传成功但未替换

### ISSUE THREAD

**Issue by wilkice** [PicGo/picgo-plugin-pic-migrater#7]
您好，这是我替换后的文件，链接未更换

![image](https://user-images.githubusercontent.com/35746578/59511958-3ee1fd00-8eea-11e9-8f08-407e376349f1.png)

PicGo 日志显示上传成功，在浏览器访问该网站能得到该照片
链接：https://i.loli.net/2019/06/14/5d039eb605e3f48334.png

![image](https://user-images.githubusercontent.com/35746578/59512053-7355b900-8eea-11e9-882e-0b5f7d9b581c.png)

插件设置如下：
![image](https://user-images.githubusercontent.com/35746578/59512300-07c01b80-8eeb-11e9-89ac-5b37fb46fe38.png)

**Comment by Molunerfinn** [comment]
单个`\`符号会引起转义问题导致可以上传但是无法替换：

https://github.com/Molunerfinn/PicGo/issues/187#issuecomment-466287938

请手动将图片链接里的`\`替换为`/`或者`\\`即可。

该问题暂时无解，等待找到解决方案后会更新。

**Comment by Wukongyongdagun** [comment]
> 单个`\`符号会引起转义问题导致可以上传但是无法替换：
> 
> [Molunerfinn/PicGo#187 (comment)](https://github.com/Molunerfinn/PicGo/issues/187#issuecomment-466287938)
> 
> 请手动将图片链接里的`\`替换为`/`或者`\\`即可。
> 
> 该问题暂时无解，等待找到解决方案后会更新。

目前版本2.3.1，OS：win10，这个问题仍然存在，链接无法替换

**Comment by wzhhhhhhhhhhhh** [comment]
> 单个`\`符号会引起转义问题导致可以上传但是无法替换：
> 
> [Molunerfinn/PicGo#187 (comment)](https://github.com/Molunerfinn/PicGo/issues/187#issuecomment-466287938)
> 
> 请手动将图片链接里的`\`替换为`/`或者`\\`即可。
> 
> 该问题暂时无解，等待找到解决方案后会更新。

目前版本1.3.2，win10，仍然存在这个问题
