### ISSUE TITLE
什么时候能兼容识别html格式？

### ISSUE THREAD

**Issue by Sdreamery** [PicGo/picgo-plugin-pic-migrater#9]
之前在微博图床有一部分上传的是html的图片格式，发现这个插件识别不了，大佬什么时候能更新一下，兼容识别一下其他格式，像picGo一样 markdown、html、URL等

**Comment by Molunerfinn** [comment]
这个涉及到复杂的正则匹配问题。只能做markdown通用的。当然后续可以开放一个配置让用户自己写正则表达式来匹配。
